apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice
  template:
    metadata:
      labels:
        app: invoice
    spec:
      containers:
        - name: invoice
          image: INVOICE_SERVICE_ECR_REPO_URI:latest
          ports:
            - containerPort: 5003
              name: "http"
---
apiVersion: v1
kind: Service
metadata:
  name: invoice-service
spec:
  selector:
    app: invoice
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5003
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: invoice-service-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: api.CUSTOM_DOMAIN
      http:
        paths:
          - path: /TENANT_NAME/invoice
            backend:
              service:
                name: invoice-service
                port:
                  number: 80
            pathType: Prefix
