AWSTemplateFormatVersion: 2010-09-09
Description: Dynamo db table to hold saas provider metadata
Resources: 
  OnboardingMetadata: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "DOMAIN_NAME"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "DOMAIN_NAME"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "SAAS_PROVIDER_METADATA"
  ProductTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "TenantId"
          AttributeType: "S"
        - AttributeName: "ProductId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "TenantId"
          KeyType: "HASH"
        - AttributeName: "ProductId"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "Product"
  CodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties: 
      RepositoryDescription: The CodeCommit repo which holds the artifacts for provisioning a new tenant
      RepositoryName: eks-tenant-saas-app-service
Outputs:
  OnboardingMetadataDdb: 
    Value: !Ref OnboardingMetadata
  CodeCommitCloneUrl: 
    Value: !GetAtt CodeCommitRepo.CloneUrlHttp
